name: Selenium CI with Docker

on:
  push:
    branches:
      - main

jobs:
  selenium-tests:
    runs-on: ubuntu-latest

    steps:
      #Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      #Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      #Build Docker image
      - name: Build Selenium Docker image
        run: docker build -t selenium-test .

      #Run Selenium tests inside Docker
      - name: Run Selenium tests
        run: docker run --name selenium-container selenium-test

      #Copy screenshots from container
      - name: Copy screenshots
        run: |
          docker cp selenium-container:/app/automation/screenshots ./screenshots

      #Upload screenshots as artifacts
      - name: Upload screenshots
        uses: actions/upload-artifact@v4
        with:
          name: selenium-screenshots
          path: screenshots
